alias vi="nvim"
alias vim="nvim"
alias gs="git status"
alias mk-sts-profile="sh /Users/john.oerterpassportinc.com/gitlab.pdev.io/passport-devops/build-utils/scripts/aws-mk-sts-profile.sh -t developer-dev -n node"
alias python="python3"
