require('plugins')

require('settings')
require('maps')

require('plugins/catppuccin')
require('plugins/formatter')
require('plugins/fugitive')
require('plugins/lspconfig')
require('plugins/lspsaga')
require('plugins/lualine')
require('plugins/neotree')
require('plugins/nvim-cmp')
require('plugins/nvim-colorizer')
require('plugins/nvim-lint')
require('plugins/nvim-treesitter')
require('plugins/rainbow-parentheses')
require('plugins/telescope')
require('plugins/trouble')
require('plugins/go')

require('languages/clojure')
