require('plugins')

require('settings')
require('maps')

require('plugins/bufferline')
require('plugins/fugitive')
require('plugins/nvim-tree')
require('plugins/lspconfig')
require('plugins/lspsaga')
require('plugins/lualine')
require('plugins/nvim-cmp')
require('plugins/nvim-colorizer')
require('plugins/rainbow-parentheses')
require('plugins/telescope')
require('plugins/trouble')
require('plugins/indent-blankline')
require('plugins/nvim-treesitter')
