require('mini.basics').setup()
require('mini.surround').setup()
require('mini.animate').setup()
require('mini.comment').setup()
require('mini.indentscope').setup()
require('mini.pairs').setup()
require('mini.statusline').setup()
